codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "25...75"

  status:
    project:
      default:
        target: 25%
        threshold: 2%
        if_ci_failed: error
    backend:
      target: 50%
      flags:
        - backend
    frontend:
      target: 15%
      flags:
        - frontend

flags:
  backend:
    paths:
      - backend/src/main/java
    carryforward: true
  frontend:
    paths:
      - frontend/src
    carryforward: true

parsers:
  go:
    enabled: no
  gcov:
    enabled: no
  javascript:
    enabled: yes
    partials_as_hits: true

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  branches:
    - master
    - develop
